## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from datetime import datetime

## Importing the dataset

In [ ]:
dataset = pd.read_excel('dataset.xlsx')
dataset = dataset.drop(columns=['Dispatching_base_num', 'locationID'], axis=1)
dataset = dataset.dropna()
dataset = dataset.reset_index(drop=True)

In [ ]:
values = dataset['Affiliated_base_num'].unique()
values.sort()

In [ ]:
values

array(['B00013', 'B00014', 'B00053', 'B00083', 'B00111', 'B00202',
       'B00208', 'B00227', 'B00254', 'B00271', 'B00272', 'B00277',
       'B00280', 'B00296', 'B00381', 'B00411', 'B00412', 'B00446',
       'B00448', 'B00477', 'B00608', 'B00628', 'B00789', 'B00837',
       'B00888', 'B01087', 'B01183', 'B01197', 'B01367', 'B01779',
       'B01803', 'B01871', 'B01875', 'B01877', 'B01899', 'B01913',
       'B01944', 'B01949', 'B01970', 'B01976', 'B01985', 'B01989',
       'B01998', 'B02003', 'B02005', 'B02016', 'B02022', 'B02054',
       'B02067', 'B02096', 'B02101', 'B02110', 'B02175', 'B02202',
       'B02207', 'B02216', 'B02222', 'B02225', 'B02253', 'B02273',
       'B02277', 'B02280', 'B02302', 'B02330', 'B02342', 'B02345',
       'B02382', 'B02401', 'B02408', 'B02424', 'B02453', 'B02468',
       'B02469', 'B02472', 'B02510', 'B02512', 'B02518', 'B02522',
       'B02524', 'B02533', 'B02534', 'B02587', 'B02588', 'B02598',
       'B02609', 'B02617', 'B02633', 'B02642', 'B02644', 'B026

In [ ]:
for i in range(len(dataset)):
  if dataset.iloc[i]['Affiliated_base_num'] in values[:25]:
    dataset['Affiliated_base_num'][i] = 0
  elif dataset.iloc[i]['Affiliated_base_num'] in values[25:50]:
    dataset['Affiliated_base_num'][i] = 1
  elif dataset.iloc[i]['Affiliated_base_num'] in values[50:75]:
    dataset['Affiliated_base_num'][i] = 2
  elif dataset.iloc[i]['Affiliated_base_num'] in values[75:100]:
    dataset['Affiliated_base_num'][i] = 3
  else:
    dataset['Affiliated_base_num'][i] = 4

<ipython-input-155-82c426125db2>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Affiliated_base_num'][i] = 0
<ipython-input-155-82c426125db2>:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Affiliated_base_num'][i] = 3
<ipython-input-155-82c426125db2>:11: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Affiliated_base_num'][i] = 4
<ipython-input-155-82c426125db2>:7: SettingWithCopyWarning: 
A value is trying

In [ ]:
dataset.groupby('Affiliated_base_num').count()

Pickup_time
Affiliated_base_num             
0                            488
1                            270
2                            103
3                           5475
4                           4614

In [ ]:
for i in range(len(dataset)):
  dt = dataset.iloc[i]['Pickup_time']
  dataset['Pickup_time'][i] = int(str(dt.hour) + str(dt.minute))

<ipython-input-157-b15084ef0249>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset['Pickup_time'][i] = int(str(dt.hour) + str(dt.minute))


## Splitting the dataset into the Training set and Test set

In [ ]:
dataset

Pickup_time Affiliated_base_num
0            2359                   0
1            2359                   3
2            2359                   3
3            2359                   3
4            2359                   3
...           ...                 ...
10945           0                   3
10946           0                   4
10947           0                   0
10948           0                   3
10949           0                   3

[10950 rows x 2 columns]

In [ ]:
dataset.Pickup_time

0        2359
1        2359
2        2359
3        2359
4        2359
         ... 
10945       0
10946       0
10947       0
10948       0
10949       0
Name: Pickup_time, Length: 10950, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(dataset.Pickup_time, dataset.Affiliated_base_num, test_size = 0.25, random_state = 0)

In [ ]:
X_train = np.array(X_train).reshape(-1,1)

In [ ]:
y_train = np.array(y_train)
y_train = y_train.astype('int')

In [ ]:
X_test = np.array(X_test).reshape(-1,1)
y_test = np.array(y_test)
y_test = y_test.astype('int')

## Training the K-NN model on the Training set

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 4]
 [3 4]
 ...
 [3 4]
 [3 4]
 [4 4]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
KNNaccuracy = accuracy_score(y_test, y_pred)

[[  2   0   0  61  44]
 [  0   0   1  48  22]
 [  0   0   0  14   7]
 [ 11   4   3 854 488]
 [ 17   4   1 732 425]]


##Training the Kernel SVM model on the Training set

In [ ]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, y_train)

SVC(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 4]
 [3 4]
 ...
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
KernelSVMaccuracy = accuracy_score(y_test, y_pred)

[[   0    0    0  107    0]
 [   0    0    0   71    0]
 [   0    0    0   21    0]
 [   0    0    0 1360    0]
 [   0    0    0 1179    0]]


##Training the Decision Tree Classification model on the Training set

In [ ]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 3]
 [3 4]
 [3 4]
 ...
 [3 4]
 [3 4]
 [4 4]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
DecisionTreeaccuracy = accuracy_score(y_test, y_pred)

[[  0   2   0  62  43]
 [  1   0   0  52  18]
 [  0   0   0  16   5]
 [  6   4   0 905 445]
 [ 13   6   0 748 412]]


##Training the Random Forest Classification model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 4]
 [3 4]
 ...
 [3 4]
 [3 4]
 [4 4]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
RandomForestaccuracy = accuracy_score(y_test, y_pred)

[[  0   2   0  57  48]
 [  1   0   0  44  26]
 [  0   0   0  16   5]
 [  5   0   3 805 547]
 [ 12   5   4 674 484]]


##Training the Naive Bayes model on the Training set

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 4]
 [3 4]
 ...
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
NaiveBayesaccuracy = accuracy_score(y_test, y_pred)

[[   0    0    0  107    0]
 [   0    0    0   71    0]
 [   0    0    0   21    0]
 [   0    0    0 1360    0]
 [   0    0    0 1179    0]]


##Training the Logistic Regression model on the Training set

In [ ]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 4]
 [3 4]
 ...
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
LogisticRegressionaccuracy = accuracy_score(y_test, y_pred)

[[   0    0    0  107    0]
 [   0    0    0   71    0]
 [   0    0    0   21    0]
 [   0    0    0 1360    0]
 [   0    0    0 1179    0]]


In [ ]:
max_accuracy = max(KNNaccuracy, KernelSVMaccuracy, DecisionTreeaccuracy, RandomForestaccuracy, NaiveBayesaccuracy, LogisticRegressionaccuracy)

In [ ]:
import time
time.ctime()
arr = time.ctime().split(" ")
ts = arr[3].split(":")
pred_time  = np.array([int(ts[0] + ts[1])])
pred_time = pred_time.reshape(-1,1)

In [ ]:
output = classifier.predict(pred_time)
output

array([3])

In [ ]:
import smtplib
import ssl
from email.message import EmailMessage

email_sender = 'f20200355@pilani.bits-pilani.ac.in'
email_password = 'wdyfqyugmjahzvct'
email_receiver = 'vinay.chamola@pilani.bits-pilani.ac.in'

In [ ]:
subject = 'Ride Requirement Update'
body = 'The base with highest requirement right now is ' + str(output)

In [ ]:
em = EmailMessage()
em['From'] = email_sender
em['To'] = email_receiver
em['Subject'] = subject
em.set_content(body)

In [ ]:
context = ssl.create_default_context()

In [ ]:
with smtplib.SMTP_SSL('smtp.gmail.com', 465, context=context) as smtp:
    smtp.login(email_sender, email_password)
    smtp.sendmail(email_sender, email_receiver, em.as_string())